# Generated by Django 3.0.5 on 2020-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200412_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
